apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: bahmni-mf-pvc
  name: bahmni-mf-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bahmni-mf-pv
spec:
  storageClassName: standard
  claimRef:
    name: bahmni-mf-pvc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/bahmni/bahmni-mf'
