#!/bin/bash
#
# openmrs        start/stop/status script
#
# chkconfig: - 64 36
# description: openmrs - Open Medical Record System
# processname: openmrs
# config: /etc/default/openmrs
# pidfile: /var/run/openmrs/openmrs.pid
### BEGIN INIT INFO
# Provides: openmrs
# Required-Start: $local_fs $remote_fs $network $named $syslog $time
# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
# Short-Description: start and stop openelis system,
# Description: openelis system
### END INIT INFO

export OPENELIS_SERVER_USER=bahmni
export OPENELIS_SERVER_RUN=/opt/openelis/bin/start.sh
export OPENELIS_SERVER_DEBUG=/opt/openelis/bin/debug.sh
export CUR_USER=`/usr/bin/whoami`

. /etc/openelis/openelis.conf

create_dirs() {
    if [[ ! -e /var/run/openelis ]]; then
        ln -s /opt/openelis/run /var/run/openelis
    fi

    if [[ ! -e /var/run/openelis/openelis ]]; then
        ln -s /opt/openelis/openelis /var/run/openelis/openelis
    fi

    if [[ ! -e /var/log/openelis ]]; then
        ln -s /opt/openelis/log /var/log/openelis
    fi
}

openelis_pid() {
        echo `ps -fe | grep 'openelis.jar' | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(openelis_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService openelis is already running (pid: $pid)\e[00m"
    else
        # Start openelis
        create_dirs
        echo -e "\e[00;32mStarting openelis\e[00m"
        if [ `user_exists $OPENELIS_SERVER_USER` = "1" ]  && [ "$CUR_USER" != "$OPENELIS_SERVER_USER" ] ;
        then
                /bin/su $OPENELIS_SERVER_USER -c $OPENELIS_SERVER_RUN
        else
                sh $OPENELIS_SERVER_RUN
        fi
  fi
  return 0
}

debug(){
    pid=$(openelis_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService openelis is already running (pid: $pid)\e[00m"
    else
        # Start openelis
        create_dirs
        echo -e "\e[00;32mStarting openelis\e[00m"
        if [ `user_exists $OPENELIS_SERVER_USER` = "1" ]  && [ "$CUR_USER" != "$OPENELIS_SERVER_USER" ] ;
        then
                /bin/su $OPENELIS_SERVER_USER -c $OPENELIS_SERVER_DEBUG
        else
                sh $OPENELIS_SERVER_DEBUG
        fi
  fi
  return 0
}

status(){
          pid=$(openelis_pid)
          if [ -n "$pid" ]; then echo -e "\e[00;32mService openelis is running with pid: $pid\e[00m"
          else echo -e "\e[00;31mService openelis is not running\e[00m"
          fi
}

stop() {
	echo -e "\e[00;31mTerminating openelis\e[00m"
	kill -9 $(openelis_pid)
}
user_exists(){
        if id -u $1 >/dev/null 2>&1; then
        echo "1"
        else
                echo "0"
        fi
}

case $1 in
	start)
	  start
	;;
    debug)
	  start
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0
