#!/bin/bash

export PACS_SERVER_USER=bahmni
export PACS_SERVER_RUN=/opt/bahmni-pacs/bin/start.sh
export PACS_SERVER_DEBUG=/opt/bahmni-pacs/bin/debug.sh
export CUR_USER=`/usr/bin/whoami`

. /opt/bahmni-pacs/etc/bahmni-pacs.conf

create_dirs() {
    if [[ ! -e /var/run/bahmni-pacs ]]; then
        ln -s /opt/bahmni-pacs/run /var/run/bahmni-pacs
    fi
}

pacs-integration_pid() {
    echo `ps -fe | grep 'pacs-integration.jar' | grep -v grep | tr -s " "|cut -d" " -f2`
}

start() {
    pid=$(pacs-integration_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService bahmni-pacs is already running (pid: $pid)\e[00m"
    else
        create_dirs
        echo -e "\e[00;32mStarting bahmni-pacs \e[00m"
        if [ `user_exists $PACS_SERVER_USER` = "1" ]  && [ "$CUR_USER" != "$PACS_SERVER_USER" ] ;
        then
            /bin/su $PACS_SERVER_USER -c $PACS_SERVER_RUN
        else
            sh $PACS_SERVER_RUN
        fi
  fi
  return 0
}

debug() {
    pid=$(pacs-integration_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService bahmni-pacs is already running (pid: $pid)\e[00m"
    else
        create_dirs
        echo -e "\e[00;32mStarting bahmni-pacs\e[00m"
        if [ `user_exists $PACS_SERVER_USER` = "1" ]  && [ "$CUR_USER" != "$PACS_SERVER_USER" ] ;
        then
            /bin/su $PACS_SERVER_USER -c $PACS_SERVER_DEBUG
        else
            sh $PACS_SERVER_DEBUG
        fi
    fi
  return 0
}

status() {
    pid=$(pacs-integration_pid)
    if [ -n "$pid" ];
    then
        echo -e "\e[00;32mService bahmni-pacs is running with pid: $pid\e[00m"
    else
        echo -e "\e[00;31mService bahmni-pacs is not running\e[00m"
    fi
}

stop() {
	echo -e "\e[00;31mTerminating bahmni-pacs\e[00m"
	kill -9 $(pacs-integration_pid)
}
user_exists(){
    if id -u $1 >/dev/null 2>&1; then
        echo "1"
    else
        echo "0"
    fi
}

case $1 in
	start)
	  start
	;;
    debug)
	  start
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0
