apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: odoo-db-dump-pvc
  name: odoo-db-dump-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-db-dump-pv
spec:
  storageClassName: standard
  claimRef:
    name: odoo-db-dump-pvc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/bahmni/odoo-db-dump'
