apiVersion: v1
kind: Service
metadata:
  name: bahmni-web
spec:
  ports:
    - name: '8091'
      port: 8091
      targetPort: 8091
  selector:
    app: bahmni-web
    environment: dev
  type: NodePort
