apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: openmrs-document-images-pvc
  name: openmrs-document-images-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openmrs-document-images-pv
spec:
  storageClassName: standard
  claimRef:
    name: openmrs-document-images-pvc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/bahmni/openmrs-document-images'
