#!/bin/bash
set -e -x

install_ansible() {
  sudo yum install -y ansible-1.9.4
}

install() {
  install_ansible
  ansible_command="cd /opt/bahmni-installer/bahmni-playbooks && chmod -x local && ansible-playbook -i local all.yml  -vvvv "
  if [ -f "/etc/bahmni-installer/setup.yml" ];
  then
    ansible_command="$ansible_command  --extra-vars '@/etc/bahmni-installer/setup.yml'"
  fi
  if [ -f "/etc/bahmni-installer/rpm_versions.yml" ];
  then
    ansible_command="$ansible_command  --extra-vars '@/etc/bahmni-installer/rpm_versions.yml'"
  fi
  eval $ansible_command
}

case $1 in
        install)
          install
        ;;
    *)
        ;;
esac
exit 0