apiVersion: v1
kind: Service
metadata:
  name: openmrsdb
spec:
  ports:
    - name: '3306'
      port: 3306
      targetPort: 3306
  selector:
    app: openmrsdb
    environment: dev
  type: ClusterIP
