#!/bin/bash
#
# bahmni-reports        start/stop/status/debug/restart script
#
# chkconfig: - 64 36
# processname: bahmni-reports
# config: /etc/default/bahmni-reports
# pidfile: /var/run/bahmni-reports/bahmni-reports.pid

export BAHMNI_REPORTS_USER=bahmni
export BAHMNI_REPORTS_RUN=/opt/bahmni-reports/bin/start.sh
export BAHMNI_REPORTS_DEBUG=/opt/bahmni-reports/bin/debug.sh
export CUR_USER=`/usr/bin/whoami`

. /etc/bahmni-reports/bahmni-reports.conf

create_dirs() {
    if [[ ! -e /var/run/bahmni-reports ]]; then
        ln -s /opt/bahmni-reports/run /var/run/bahmni-reports
    fi

    if [[ ! -e /var/run/bahmni-reports/bahmni-reports ]]; then
        ln -s /opt/bahmni-reports/bahmni-reports /var/run/bahmni-reports/bahmni-reports
    fi

    if [[ ! -e /var/log/bahmni-reports ]]; then
        ln -s /opt/bahmni-reports/log /var/log/bahmni-reports
    fi
}

bahmni_reports_pid() {
        echo `ps -fe | grep 'bahmni-reports.jar' | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(bahmni_reports_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService bahmni-reports is already running (pid: $pid)\e[00m"
    else
        # Start bahmni-reports
        create_dirs
        echo -e "\e[00;32mStarting bahmni-reports\e[00m"
        if [ `user_exists $BAHMNI_REPORTS_USER` = "1" ]  && [ "$CUR_USER" != "$BAHMNI_REPORTS_USER" ] ;
        then
                /bin/su $BAHMNI_REPORTS_USER -c $BAHMNI_REPORTS_RUN
        else
                sh $BAHMNI_REPORTS_RUN
        fi
  fi
  return 0
}

debug(){
    pid=$(bahmni_reports_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService bahmni-reports is already running (pid: $pid)\e[00m"
    else
        # Start bahmni-reports
        create_dirs
        echo -e "\e[00;32mStarting bahmni-reports\e[00m"
        if [ `user_exists $BAHMNI_REPORTS_USER` = "1" ]  && [ "$CUR_USER" != "$BAHMNI_REPORTS_USER" ] ;
        then
                /bin/su $BAHMNI_REPORTS_USER -c $BAHMNI_REPORTS_DEBUG
        else
                sh $BAHMNI_REPORTS_DEBUG
        fi
  fi
  return 0
}

status(){
          pid=$(bahmni_reports_pid)
          if [ -n "$pid" ]; then echo -e "\e[00;32mService bahmni-reports is running with pid: $pid\e[00m"
          else echo -e "\e[00;31mService bahmni-reports is not running\e[00m"
          fi
}

stop() {
	echo -e "\e[00;31mTerminating bahmni-reports\e[00m"
	kill -9 $(bahmni_reports_pid)
}
user_exists(){
        if id -u $1 >/dev/null 2>&1; then
        echo "1"
        else
                echo "0"
        fi
}

case $1 in
	start)
	  start
	;;
    debug)
	  debug
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0
