#!/bin/bash
#
# openelis        start/stop/status/debug/restart script
#
# chkconfig: - 64 36
# processname: bahmni-erp-connect
# config: /etc/default/bahmni-erp-connect
# pidfile: /var/run/bahmni-erp-connect/bahmni-erp-connect.pid

export BAHMNI_ERP_CONNECT_USER=bahmni
export BAHMNI_ERP_CONNECT_RUN=/opt/bahmni-erp-connect/bin/start.sh
export BAHMNI_ERP_CONNECT_DEBUG=/opt/bahmni-erp-connect/bin/debug.sh
export CUR_USER=`/usr/bin/whoami`

. /etc/bahmni-erp-connect/bahmni-erp-connect.conf

create_dirs() {
    if [[ ! -e /var/run/bahmni-erp-connect ]]; then
        ln -s /opt/bahmni-erp-connect/run /var/run/bahmni-erp-connect
    fi

    if [[ ! -e /var/run/bahmni-erp-connect/bahmni-erp-connect ]]; then
        ln -s /opt/bahmni-erp-connect/bahmni-erp-connect /var/run/bahmni-erp-connect/bahmni-erp-connect
    fi

    if [[ ! -e /var/log/bahmni-erp-connect ]]; then
        ln -s /opt/bahmni-erp-connect/log /var/log/bahmni-erp-connect
    fi
}

bahmni_erp_connect_pid() {
        echo `ps -fe | grep 'bahmni-erp-connect.jar' | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(bahmni_erp_connect_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService bahmni-erp-connect is already running (pid: $pid)\e[00m"
    else
        # Start bahmni-erp-connect
        create_dirs
        echo -e "\e[00;32mStarting bahmni-erp-connect\e[00m"
        sh $BAHMNI_ERP_CONNECT_RUN
  fi
  exit 0
}

debug(){
    pid=$(bahmni_erp_connect_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService bahmni-erp-connect is already running (pid: $pid)\e[00m"
    else
        # Start bahmni-erp-connect
        create_dirs
        echo -e "\e[00;32mStarting bahmni-erp-connect\e[00m"
        if [ `user_exists $BAHMNI_ERP_CONNECT_USER` = "1" ]  && [ "$CUR_USER" != "$BAHMNI_ERP_CONNECT_USER" ] ;
        then
                runuser -u $BAHMNI_ERP_CONNECT_USER $BAHMNI_ERP_CONNECT_DEBUG
        else
                sh $BAHMNI_ERP_CONNECT_DEBUG
        fi
    fi
  exit 0
}

status(){
          pid=$(bahmni_erp_connect_pid)
          if [ -n "$pid" ]; then echo -e "\e[00;32mService bahmni-erp-connect is running with pid: $pid\e[00m"
          else echo -e "\e[00;31mService bahmni-erp-connect is not running\e[00m"
          exit 3
          fi
}

stop() {
	echo -e "\e[00;31mTerminating bahmni-erp-connect\e[00m"
	kill -9 $(bahmni_erp_connect_pid)
	rm -f /var/run/bahmni-erp-connect/bahmni-erp-connect.pid
    return
}
user_exists(){
        if id -u $1 >/dev/null 2>&1; then
        echo "1"
        else
        echo "0"
        fi
}

case $1 in
	start)
	  start
	;;
    debug)
	  debug
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0
