name: Build and upload artifact
on:
  push:
    branches:
      - master
    paths:
      - "core/**"

env:
  ORG_NAME: Bahmni
  EVENT_TYPE: bahmni-embedded-tomcat-trigger
  BAHMNI_VERSION: 0.94

jobs:
  build-upload-artifact:
    name: Build and upload embedded Tomcat Server artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate Artifact
        run: ./gradlew -PbahmniRelease=${BAHMNI_VERSION} :core:clean :core:build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bahmni-embedded-tomcat
          path: core/build/libs/core-1.0-SNAPSHOT.jar

  trigger-dependent-repos:
    name: Trigger Workflows
    needs: build-upload-artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependent-repos: ["OpenElis", "openerp-atomfeed-service", "bahmni-reports"]
    steps:
      - name: Create repository_dispatch
        env:
          REPOSITORY_NAME: ${{ matrix.dependent-repos }}
        run: |
          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
          if [ $trigger_result == 204 ];then
            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
          else
            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
            cat trigger_response.txt
            exit 1
          fi
