name: DCM4CHEE-Build and Publish 
on:
  push:
    branches:
      - master
    paths:
      - 'bahmni-pacs/**'
      - '.github/workflows/dcm4chee_build_publish.yml'
env:
  DCM4CHEE_VERSION: 1.0.0

jobs:
  docker-build-publish:
    name: Docker Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: bahmni-pacs/
          file: bahmni-pacs/docker/dcm4chee/Dockerfile
          no-cache: true
          push: true
          tags: bahmni/dcm4chee:${{env.DCM4CHEE_VERSION}}-${{github.run_number}},bahmni/dcm4chee:latest
