name: Trivy Scan
on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - 'atomfeed-console/**'
      - '.github/workflows/atomfeed_console_build_publish.yaml'
      - "core/**"
      - 'bahmni-pacs/**'
      - '.github/workflows/dcm4chee_build_publish.yml'
      - 'bahmni-proxy/**'
      - '.github/workflows/proxy_image_build_publish.yml'
  pull_request:
    branches: [ '*' ]
    types: [opened, synchronize, reopened]
    

jobs:
  Trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trivy Scan
        run:  ./.github/trivy_scan.sh